/**
 * Regenerates registry/__index__.tsx from the registry-*.ts sources.
 *
 * The committed index claimed to be autogenerated by this script, but the
 * script was never in this repo — the 12k-line file had been vendored in and
 * hand-edited since. This reconstructs it, so adding a component means adding
 * a registry entry and re-running, not editing generated code.
 *
 * Run with: pnpm --filter www registry:build
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { registry } from "../registry/index";

type RegistryFile = string | { path: string; target?: string; type?: string };

type RegistryItem = {
  name: string;
  type: string;
  description?: string;
  categories?: string[];
  registryDependencies?: string[];
  files?: RegistryFile[];
  meta?: Record<string, unknown>;
};

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT = path.join(ROOT, "registry", "__index__.tsx");

/** A valid bare identifier can stay unquoted, matching the previous output. */
function key(name: string) {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function literal(value: unknown, indent: string): string {
  if (value === undefined) {
    return "undefined";
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }
    const inner = value
      .map((v) => `${indent}  ${literal(v, `${indent}  `)}`)
      .join(",\n");
    return `[\n${inner},\n${indent}]`;
  }
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).sort(
      ([a], [b]) => a.localeCompare(b),
    );
    if (entries.length === 0) {
      return "{}";
    }
    const inner = entries
      .map(([k, v]) => `${indent}  ${key(k)}: ${literal(v, `${indent}  `)}`)
      .join(",\n");
    return `{\n${inner},\n${indent}}`;
  }
  return JSON.stringify(value);
}

function normalizeFiles(item: RegistryItem) {
  return (item.files ?? []).map((file) => {
    if (typeof file === "string") {
      return { path: file, target: "", type: item.type };
    }
    return {
      path: file.path.startsWith("registry/")
        ? file.path
        : `registry/default/${file.path}`,
      target: file.target ?? "",
      type: file.type ?? item.type,
    };
  });
}

function entryFor(item: RegistryItem) {
  const files = normalizeFiles(item);
  const importPath = files[0]
    ? `@/${files[0].path.replace(/^registry\//, "registry/")}`
    : undefined;

  // The lazy import is emitted verbatim rather than built from the item, so
  // the generated file keeps the exact runtime behaviour it had before.
  const lazy = importPath
    ? `React.lazy(async () => {
      const mod = await import(
        "${importPath}"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    })`
    : "undefined";

  return `  ${key(item.name)}: {
    categories: ${literal(item.categories, "    ")},
    component: ${lazy},
    description: ${JSON.stringify(item.description ?? "")},
    files: ${literal(files, "    ")},
    meta: ${literal(item.meta, "    ")},
    name: ${JSON.stringify(item.name)},
    registryDependencies: ${literal(item.registryDependencies, "    ")},
    type: ${JSON.stringify(item.type)},
  },`;
}

async function main() {
  const items = registry.items as unknown as RegistryItem[];
  const seen = new Set<string>();
  const entries: string[] = [];

  for (const item of items) {
    if (seen.has(item.name)) {
      console.warn(`duplicate registry item skipped: ${item.name}`);
      continue;
    }
    seen.add(item.name);
    entries.push(entryFor(item));
  }

  const body = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

// biome-ignore lint/suspicious/noExplicitAny: Auto-generated registry index with dynamic component types
export const Index: Record<string, any> = {
${entries.join("\n")}
};
`;

  await fs.writeFile(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${entries.length} items`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
