/**
 * Registry Categories Type Definition
 *
 * This file defines all valid categories that can be used in registry items.
 * All categories are treated equally - no distinction between component and tag categories.
 */

// All registry categories in display order
export const registryCategories = [
  // UI components
  "accordion",
  "alert",
  "alert dialog",
  "ask user questions",
  "aspect ratio",
  "attachment",
  "autocomplete",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "button group",
  "calendar",
  "card",
  "chart",
  "chat message",
  "checkbox",
  "checkbox group",
  "code block",
  "collapsible",
  "color picker",
  "combobox",
  "command",
  "command menu",
  "context menu",
  "crm table",
  "dialog",
  "dropdown",
  "empty state",
  "field",
  "fieldset",
  "file diff",
  "file thumbnail",
  "form",
  "frame",
  "group",
  "hover card",
  "image generation",
  "inline citations",
  "input",
  "input copy",
  "input dissolve",
  "input group",
  "input message",
  "input otp",
  "item",
  "kbd",
  "label",
  "logo carousel",
  "magnetic dropzone",
  "marker",
  "menu",
  "menubar",
  "message scroller",
  "meter",
  "mobile drawer",
  "number field",
  "pagination",
  "plan card",
  "popover",
  "preview card",
  "progress",
  "radio group",
  "resizable",
  "scroll area",
  "select",
  "separator",
  "sheet",
  "sidebar menu",
  "skeleton",
  "slider",
  "spinner",
  "streaming text",
  "switch",
  "table",
  "tabs",
  "tabs subtle",
  "task list",
  "textarea",
  "thinking indicator",
  "thinking steps",
  "toast",
  "toggle",
  "toggle group",
  "toolbar",
  "tooltip",
  // Features and states
  "async",
  "copy",
  "disabled",
  "error",
  "file",
  "filter",
  "info",
  "loading",
  "multiselect",
  "password",
  "search",
  "sort",
  "success",
  "tag",
  "tanstack",
  "text editor",
  "time",
  "timezone",
  "upload",
  "validation",
  "warning",
  "zod",
] as const;

export type RegistryCategory = (typeof registryCategories)[number];

// Helper function to get category sort order
export function getCategorySortOrder(category: string): number {
  const index = registryCategories.indexOf(category as RegistryCategory);
  return index === -1 ? Number.POSITIVE_INFINITY : index;
}

// Helper function to validate if a string is a valid RegistryCategory
export function isValidRegistryCategory(
  category: string,
): category is RegistryCategory {
  return registryCategories.includes(category as RegistryCategory);
}
